# This is the global configuration file for carbide-api that is shared
# between all environments.
# Each environment can overwrite certain parameters of this file via a
# carbide-api-site-config.toml file. Those are placed in the `envs/` folder
# for the respective environment

listen = "[::]:1079"
metrics_endpoint = "[::]:1080"
alt_metric_prefix = "forge_"
profiler_endpoint = "[::]:1081"
database_url = "postgres://replaced-by-env-var"
asn = 4294967000
initial_dpu_agent_upgrade_policy = "up_only"
dpu_nic_firmware_intial_update_enabled = false
dpu_nic_firmware_reprovision_update_enabled = true
dpu_nic_firmware_update_version = { "BlueField SoC" = "24.42.1000", "BlueField-3 SmartNIC Main Card" = "32.42.1000" }
max_concurrent_machine_updates = 10
nvue_enabled = true
dhcp_servers = []
route_servers = []
attestation_enabled = true

anycast_site_prefixes = ["0.0.0.0/0"]

[host_health]
hardware_health_reports = "MonitorOnly"

[site_explorer]
enabled = true
create_machines = true

[firmware_global]
autoupdate = true

[machine_identity]
enabled = true
current_encryption_key_id = "kv1"
algorithm = "ES256"

[tls]
identity_pemfile_path = "/var/run/secrets/spiffe.io/tls.crt"
identity_keyfile_path = "/var/run/secrets/spiffe.io/tls.key"
root_cafile_path = "/var/run/secrets/spiffe.io/ca.crt"
admin_root_cafile_path = "/etc/forge/carbide-api/site/admin_root_cert_pem"

[auth]
permissive_mode = false
casbin_policy_file = "/etc/forge/carbide-api/casbin-policy.csv"

[auth.trust]
spiffe_trust_domain = "forge.local"
spiffe_service_base_paths = [
  "/forge-system/sa/",
  "/default/sa/",
  "/elektra-site-agent/sa/",
]
spiffe_machine_base_path = "/forge-system/machine/"
additional_issuer_cns = []

[machine_state_controller]
failure_retry_time = "45m"

[network_security_group]
stateful_acls_enabled = false
max_network_security_group_size = 200

[machine_validation_config]
enabled = true
test_selection_mode = "EnableAll"
