apiVersion: v1
kind: ConfigMap
metadata:
  name: carbide-bmc-proxy-config-files
  namespace: {{ include "carbide-bmc-proxy.namespace" . }}
  labels:
    {{- include "carbide-bmc-proxy.labels" . | nindent 4 }}
data:
  carbide-api-config.toml: |
    {{- if .Values.configFiles.carbideApiConfig }}
    {{- .Values.configFiles.carbideApiConfig | nindent 4 }}
    {{- else }}
    {{- .Files.Get "files/carbide-api-config.toml" | nindent 4 }}
    {{- end }}
{{- if .Values.siteConfig.enabled }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: carbide-bmc-proxy-site-config-files
  namespace: {{ include "carbide-bmc-proxy.namespace" . }}
  labels:
    {{- include "carbide-bmc-proxy.labels" . | nindent 4 }}
data:
  carbide-api-site-config.toml: |
    {{- with .Values.siteConfig.carbideApiSiteConfig }}
    {{- . | nindent 4 }}

    {{- end }}
    [bmc_proxy]
    listen = {{ .Values.bmcProxy.listen | quote }}
    allowed_principals = [
    {{- range $index, $principal := .Values.bmcProxy.allowedPrincipals }}
      {{- if $index }},{{ end }}
      {{ $principal | quote }}
    {{- end }}
    ]
{{- end }}
{{- if .Values.vaultClusterInfo }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.envFrom.vaultClusterInfo.configMapName }}
  namespace: {{ include "carbide-bmc-proxy.namespace" . }}
  annotations:
    argocd.argoproj.io/sync-wave: "-10"
  labels:
    {{- include "carbide-bmc-proxy.labels" . | nindent 4 }}
data:
  {{- range $key, $value := .Values.vaultClusterInfo }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
{{- end }}
{{- if .Values.databaseConfig }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.envFrom.databaseConfig.configMapName }}
  namespace: {{ include "carbide-bmc-proxy.namespace" . }}
  annotations:
    argocd.argoproj.io/sync-wave: "-10"
  labels:
    {{- include "carbide-bmc-proxy.labels" . | nindent 4 }}
data:
  {{- range $key, $value := .Values.databaseConfig }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
{{- end }}
